[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python3 -m venv /app/.venv",
  "/app/.venv/bin/pip install flask==3.1.0"
]

[start]
cmd = "/app/.venv/bin/python api/app.py $PORT"
